Improve module loadfile() error messages
Have the module package loader return the loadfile() error for file system modules,
and report the error from the calling script, rather than globals.lua.

This give marginally better errors when require()'ing modules with syntax errors.
The error will appear in the package loader list with the correct call site.

     Error: /Users/blah/premake5.lua:7: module 'wee' not found:
         no field package.preload['wee']
         load error /Users/blah/modules/wee/wee.lua:3: '=' expected near '<eof>'
	 ....